#!/usr/bin/env python3
"""
refresh_brief_sources.py — Sync the Sources appendix in an opportunity's Word briefs.

For each .docx in <opportunity>/04_artifacts/, append (or replace) a
"Sources (auto-generated)" section listing every ingested primary source
from 01_sources/. Each entry: title, publisher, capture date, hyperlink.

The section is delimited by sentinel paragraphs so re-running the script
replaces only the auto-generated block, leaving the rest of the brief intact.

Usage:
    python refresh_brief_sources.py --opportunity PMTEC-USINDOPACOM
    python refresh_brief_sources.py --opportunity PMTEC-USINDOPACOM --dry-run
"""

import argparse
import re
import sys
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

SCRIPT_DIR = Path(__file__).parent
VAULT_ROOT = SCRIPT_DIR.parent
OPP_ROOT = VAULT_ROOT / "opportunities"

SENTINEL_START = "── Sources (auto-generated by refresh_brief_sources.py — do not edit by hand) ──"
SENTINEL_END = "── End auto-generated sources ──"


# ── Frontmatter parsing ─────────────────────────────────────────────────

_FM_RE = re.compile(r'^---\n(.*?)\n---', re.DOTALL)


def _parse_frontmatter(text: str) -> dict:
    m = _FM_RE.match(text)
    if not m:
        return {}
    out: dict = {}
    for line in m.group(1).splitlines():
        m2 = re.match(r'^([A-Za-z0-9_]+):\s*(.*)$', line)
        if m2:
            key, value = m2.group(1), m2.group(2).strip().strip('"').strip("'")
            out[key] = value
    return out


def _collect_sources(opp_dir: Path) -> list[dict]:
    sources = []
    for src in sorted((opp_dir / "01_sources").glob("*.md")):
        fm = _parse_frontmatter(src.read_text(encoding="utf-8"))
        if not fm or fm.get("type") != "source":
            continue
        sources.append({
            "title":     fm.get("title", src.stem),
            "url":       fm.get("url", ""),
            "publisher": fm.get("publisher", ""),
            "captured":  fm.get("captured", ""),
            "pub_date":  fm.get("publication_date", ""),
            "tier":      fm.get("source_tier", ""),
            "filename":  src.name,
        })
    return sources


# ── Word document manipulation ──────────────────────────────────────────

def _add_hyperlink(paragraph, url: str, text: str) -> None:
    """Add a real Word hyperlink (not just a text run) to a paragraph."""
    if not url:
        paragraph.add_run(text)
        return
    part = paragraph.part
    r_id = part.relate_to(url,
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink",
        is_external=True,
    )
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), r_id)

    new_run = OxmlElement("w:r")
    rpr = OxmlElement("w:rPr")
    # Style as a hyperlink (blue + underline) via rPr
    color = OxmlElement("w:color"); color.set(qn("w:val"), "0563C1"); rpr.append(color)
    u = OxmlElement("w:u"); u.set(qn("w:val"), "single"); rpr.append(u)
    new_run.append(rpr)

    t = OxmlElement("w:t")
    t.text = text
    t.set(qn("xml:space"), "preserve")
    new_run.append(t)

    hyperlink.append(new_run)
    paragraph._p.append(hyperlink)


def _remove_existing_block(doc: Document) -> int:
    """Delete paragraphs between sentinel-start and sentinel-end (inclusive). Returns count removed."""
    body = doc.element.body
    paragraphs = list(doc.paragraphs)

    start_idx = None
    end_idx = None
    for i, p in enumerate(paragraphs):
        if SENTINEL_START in p.text:
            start_idx = i
        if start_idx is not None and SENTINEL_END in p.text:
            end_idx = i
            break

    if start_idx is None:
        return 0
    if end_idx is None:
        end_idx = len(paragraphs) - 1

    removed = 0
    for p in paragraphs[start_idx:end_idx + 1]:
        body.remove(p._p)
        removed += 1
    return removed


def _append_sources_section(doc: Document, sources: list[dict]) -> None:
    """Append the auto-generated Sources section to the document."""
    from docx.shared import Pt, RGBColor

    def _para(text="", *, bold=False, italic=False, size=None, color=None, page_break_before=False):
        p = doc.add_paragraph()
        if page_break_before:
            p.paragraph_format.page_break_before = True
        if text:
            r = p.add_run(text)
            if bold:   r.bold = True
            if italic: r.italic = True
            if size:   r.font.size = Pt(size)
            if color:  r.font.color.rgb = RGBColor(*color)
        return p

    # Top-of-section sentinel (italic, small, page break)
    _para(SENTINEL_START, italic=True, size=9, color=(0x80, 0x80, 0x80),
          page_break_before=True)

    # Section heading — direct formatting (avoids missing-style errors)
    _para("Sources", bold=True, size=18)

    _para(
        f"All primary and secondary sources captured into this opportunity's "
        f"01_sources/ folder ({len(sources)} total). Each entry is hyperlinked "
        f"to the live source URL. Re-generate via "
        f"_scripts/refresh_brief_sources.py.",
        italic=True, size=10,
    )

    for i, s in enumerate(sources, 1):
        # Entry title line — numbered, bold title + hyperlink
        p = doc.add_paragraph()
        num_run = p.add_run(f"{i}. ")
        num_run.bold = True
        title_run = p.add_run(s["title"])
        title_run.bold = True
        p.add_run("\n   ")
        _add_hyperlink(p, s["url"], s["url"])

        # Metadata line (italic, smaller)
        meta = doc.add_paragraph()
        meta_run = meta.add_run(
            f"   Publisher: {s['publisher']}   ·   "
            f"Tier {s['tier']}   ·   "
            f"Captured: {s['captured']}"
            f"{('   ·   Pub: ' + s['pub_date']) if s['pub_date'] else ''}   ·   "
            f"Local: 01_sources/{s['filename']}"
        )
        meta_run.italic = True
        meta_run.font.size = Pt(9)
        meta_run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    # Bottom sentinel
    _para(SENTINEL_END, italic=True, size=9, color=(0x80, 0x80, 0x80))


def refresh_brief(docx_path: Path, sources: list[dict], dry_run: bool = False) -> dict:
    doc = Document(docx_path)
    removed = _remove_existing_block(doc)
    if dry_run:
        return {"path": docx_path, "removed": removed, "would_add": len(sources)}
    _append_sources_section(doc, sources)
    doc.save(docx_path)
    return {"path": docx_path, "removed": removed, "added": len(sources)}


# ── Main ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--opportunity", required=True, metavar="ID")
    parser.add_argument("--dry-run", action="store_true",
        help="Report what would change without writing")
    args = parser.parse_args()

    opp_dir = OPP_ROOT / args.opportunity
    if not opp_dir.is_dir():
        print(f"ERROR: Opportunity folder not found: {opp_dir}")
        sys.exit(1)

    artifacts = opp_dir / "04_artifacts"
    if not artifacts.is_dir():
        print(f"ERROR: 04_artifacts/ not found in {opp_dir}")
        sys.exit(1)

    docx_files = sorted(artifacts.glob("*.docx"))
    if not docx_files:
        print(f"No .docx files in {artifacts}")
        return

    sources = _collect_sources(opp_dir)
    print(f"Found {len(sources)} ingested sources in 01_sources/")
    print(f"Updating {len(docx_files)} Word file(s):")
    print()

    for d in docx_files:
        result = refresh_brief(d, sources, dry_run=args.dry_run)
        action = "would add" if args.dry_run else "added"
        rel = d.relative_to(VAULT_ROOT)
        print(f"  {rel}")
        print(f"    removed prior auto-block: {result['removed']} paragraph(s)")
        print(f"    {action}: {len(sources)} source entries")
        print()


if __name__ == "__main__":
    main()
